export const GETALLWORKS_REQUEST = 'GETALLWORKS_REQUEST'
export const GETALLWORKS_SUCCESS = 'GETALLWORKS_SUCCESS'
export const GETALLWORKS_FAILED = 'GETALLWORKS_FAILED'

export const GETEACHWORK_REQUEST = 'GETEACHWORK_REQUEST'
export const GETEACHWORK_SUCCESS = 'GETEACHWORK_SUCCESS'
export const GETEACHWORK_FAILED = 'GETEACHWORK_FAILED'

export const POST_WORK_REQUEST = 'POST_WORK_REQUEST'
export const POST_WORK_SUCCESS = 'POST_WORK_SUCCESS'
export const POST_WORK_FAIL = 'POST_WORK_FAIL'
